
name: Run Selenium On GitHub Action
on:
  push:
    branches:
      - master
jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out repo
        uses: actions/checkout@v3
      - name: Setting up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Selenium
        run: pip install selenium
      
      - name: Running the Chrome Test
        run: python3 Selenium_Chrome_Website_Test.py

      - name: Running the Edge Test
        run: python3 Selenium_Edge_Website_Test.py

      - name: Running the Firefox Test
        run: python3 Selenium_Firefox_Website_Test.py

      - name: TEAM ROCKET!!!
        run: ./TeamRocket.sh
